### ISSUE TITLE
Screen goes black with 

### ISSUE THREAD

**Issue by The-Original-Reth** [michael5r/mmm-nest-status#16]
Hello,
when I start magic mirror with mmm-nest-status I get the following errror. When I remove mmm-nest status it works find. Please help.

pi@raspberrypi:~/MagicMirror $ npm run start

> magicmirror@2.17.1 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[28.12.2021 12:55.10.167] [LOG]   Starting MagicMirror: v2.17.1
[28.12.2021 12:55.10.174] [LOG]   Loading config ...
[28.12.2021 12:55.10.180] [LOG]   Loading module helpers ...
[28.12.2021 12:55.10.192] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/mmm-nest-status/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[28.12.2021 12:55.10.193] [LOG]   Loading module helpers ...
[28.12.2021 12:55.10.196] [ERROR] App threw an error during load
[28.12.2021 12:55.10.198] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/mmm-nest-status/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/mmm-nest-status/node_helper.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[28.12.2021 12:55.10.200] [ERROR] Whoops! There was an uncaught exception...
[28.12.2021 12:55.10.206] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/mmm-nest-status/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/mmm-nest-status/node_helper.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/mmm-nest-status/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[28.12.2021 12:55.10.209] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[28.12.2021 12:55.10.209] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[28.12.2021 12:55.10.405] [LOG]   Launching application.

**Comment by relm923** [comment]
https://github.com/michael5r/mmm-nest-status/issues/14

**Comment by michael5r** [comment]
Fixed in the latest version:

https://github.com/michael5r/mmm-nest-status/pull/21
